services:
  backend:
    container_name: gb-backend
    build:
      context: ./backend
    expose:
      - ${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      PORT: ${BACKEND_PORT}
    networks:
      - graph-board-network

  frontend:
    container_name: gb-frontend
    build:
      context: ./frontend
    expose:
      - ${FRONTEND_PORT}
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      PORT: ${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - graph-board-network

  nginx:
    container_name: gb-nginx
    build:
      context: ./nginx
      args:
        CONF_TEMPLATE_FILE: nginx-dev.conf.template
    depends_on:
      - backend
      - frontend
    ports:
      - "${NGINX_EXPOSED_PORT}:${NGINX_INNER_PORT}"
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      MONGO_PORT: ${MONGO_PORT}
      NGINX_INNER_PORT: ${NGINX_INNER_PORT}
      NGINX_EXPOSED_PORT: ${NGINX_EXPOSED_PORT}
    entrypoint: ["/etc/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - graph-board-network

networks:
  graph-board-network:
    driver: bridge
