backend:
  container_name: gb-backend
  build:
    context: ./backend
  ports:
    - "8000:8000"
  environment:
    DATABASE_URL: "postgresql://user:password@db:5432/card_db"
  volumes:
    - ./backend:/app
  depends_on:
    - db

frontend:
  container_name: gb-frontend
  build:
    context: ./frontend
  expose:
    - "3000"
  environment:
    BACKEND_URL: "http://nginx:80"
  volumes:
    - ./frontend:/app
    - /app/node_modules0
