version: "3.8"

services:
  db:
    image: postgres:13
    container_name: gb-postgres
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - graph-board-network

  backend:
    container_name: gb-backend
    build:
      context: ./backend
    expose:
      - ${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      PORT: ${BACKEND_PORT}
      DATABASE_URL: "postgresql://user:password@db:5432/card_db"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - graph-board-network

  frontend:
    container_name: gb-frontend
    build:
      context: ./frontend
    expose:
      - ${FRONTEND_PORT}
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      PORT: ${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - graph-board-network

  nginx:
    container_name: gb-nginx
    build:
      context: ./nginx
      args:
        CONF_TEMPLATE_FILE: nginx-dev.conf.template
    depends_on:
      - backend
      - frontend
    ports:
      - "${NGINX_EXPOSED_PORT}:${NGINX_INNER_PORT}"
    networks:
      - graph-board-network

volumes:
  postgres_data:

networks:
  graph-board-network:
    driver: bridge
