name: GitHub Deploy Stage
run-name: ${{ github.actor }} deploying to stage
on: workflow_dispatch

jobs:
  Deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: pull
        uses: actions/checkout@v4
      - name: run container
        env:
        run: bash stage.sh
